apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-sm
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: python-web
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
